#!/bin/sh
UI=$(jq -r '.experimental.clash_api.external_ui_download_url' /app/config.json|grep -oE 'metacubexd|Yacd-meta')
INSTALL_DIR=$(jq -r '.experimental.clash_api.external_ui' /app/config.json)
METACUBEX_LINK="https://github.com/MetaCubeX/metacubexd.git"
YACD_LINK="https://github.com/MetaCubeX/Yacd-meta.git"
BRANCH="gh-pages"
PROXY="https://mirror.ghproxy.com"
#update or replace the ui via git
if [ "${INSTALL_DIR}" != "null" ]
then
    #update ui
    cd ${INSTALL_DIR}
    git pull
    #replace ui
    if [ $? -ne 0 ]
    then
        if [[ "${UI}" == "Yacd-meta" || "${UI}" == "null" ]]
        then
            rm -rf ${INSTALL_DIR}
            cd /app
            git clone -b ${BRANCH} ${PROXY}/${YACD_LINK}
            mv Yacd-meta ${INSTALL_DIR}
        elif [ "${UI}" == "metacubexd" ]
        then
            rm -rf ${INSTALL_DIR}
            cd /app
            git clone -b ${BRANCH} ${PROXY}/${METACUBEX_LINK}
            mv metacubexd ${INSTALL_DIR}
        fi
    fi
fi

