#!/bin/sh
#update routes
curl -Lo /app/bird/routes4.conf ${GH_PROXY}/https://github.com/dalamudx/nchnroutes/releases/download/latest/routes4.conf
curl -Lo /app/bird/routes6.conf ${GH_PROXY}/https://github.com/dalamudx/nchnroutes/releases/download/latest/routes6.conf
birdc configure
#update geo files
curl -Lo /app/sing-box/geoip.db ${GEO_PROXY}/gh/MetaCubeX/meta-rules-dat@release/geoip.db
curl -Lo /app/sing-box/geosite.db ${GEO_PROXY}/gh/MetaCubeX/meta-rules-dat@release/geosite.db
#update ui
/bin/sh /app/ui